service: noma-whitelist-verification

custom:
  USER_POOL_WEB_CLIENT_NAME: ${cf:noma-whitelist-cognito-${opt:stage,self:provider.stage}.UserPoolWebClient}
  USER_POOL_ID: ${cf:noma-whitelist-cognito-${opt:stage,self:provider.stage}.UserPoolId}
  REGION: ${env:REGION, 'eu-central-1'}

provider:
  name: aws
  runtime: nodejs14.x
  region: ${self:custom.REGION}

  httpApi:
    cors: true      
    authorizers:
      serviceAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        cors: true
        issuerUrl: https://cognito-idp.eu-central-1.amazonaws.com/${self:custom.USER_POOL_ID}
        audience:
          - ${self:custom.USER_POOL_WEB_CLIENT_NAME}

functions:
  verify:
    handler: handler.verify
    events:
      - httpApi:
          path: /verify
          method: get
          authorizer: serviceAuthorizer         
